CREATE DATABASE SELL_STAGE
GO

USE SELL_STAGE
GO

CREATE TABLE ST_CUSTOMERS
(
	CUSTOMER_ID bigint NULL,
	CUSTOMER_CREATED_AT datetime NULL
)
GO

CREATE TABLE ST_CURRENCY_CODES
(
	CURRENCY_CODE_ID int identity(1,1) NOT NULL,
	CURRENCY_CODE_NAME varchar(3) NULL
)
GO

CREATE TABLE ST_TEMP_CURRENCY_CODES
(
	CURRENCY_CODE_NAME varchar(3) NULL
)
GO

CREATE TABLE ST_FULFILLMENT_STATUS
(
	FULFILLMENT_STATUS_ID int identity(1,1) NOT NULL,
	FULFILLMENT_STATUS_NAME varchar(20) NULL
)
GO

CREATE TABLE ST_TEMP_FULFILLMENT_STATUS
(
	FULFILLMENT_STATUS_NAME varchar(20) NULL
)
GO


CREATE TABLE ST_ORDERS
(
	ORDER_ID bigint NULL,
	ORDER_CREATED_AT datetime NULL,
	CURRENCY_CODE_ID int NULL,
	ORDER_SUBTOTAL numeric(10, 2) NULL,
	ORDER_TOTAL numeric(10, 2) NULL,
	FULFILLMENT_STATUS_ID int NULL,
	ORDER_CUSTOMER_ID bigint NULL,
	ORDER_CUSTOMER_CREATED_AT datetime NULL
)
GO

CREATE TABLE ST_JSON
(
	ID bigint NULL,
	PROCESSED_AT datetime NULL,
	CURRENCY_CODE varchar(3) NULL,
	CURRENT_SUBTOTAL_PRICE_SET_AMOUNT numeric(10, 2) NULL,
	ORIGINAL_TOTAL_DUTIES_SET varchar(200) NULL,
	ORIGINAL_TOTAL_PRICE_SET_AMOUNT numeric(10, 2) NULL,
	DISPLAY_FULFILLMENT_STATUS varchar(20) NULL,
	CUSTOMER_ID bigint NULL,
	CUSTOMER_CREATED_AT datetime NULL
)
GO
